// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // `tsx`, not `ts-node`: the generated Prisma client imports its own modules
    // with ESM-style `.js` specifiers that resolve to `.ts` files on disk, and
    // ts-node's CJS resolver does not rewrite them.
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
